import { Test, TestingModule } from '@nestjs/testing';
import {
  INestApplication,
  NotFoundException,
  ValidationPipe,
} from '@nestjs/common';
import * as request from 'supertest';
import { ConfigModule } from '@nestjs/config';

import { ContentPlanService } from './contentPlan.service';
import { ContentPlanController } from './contentPlan.controller';
import { PrismaService } from '../../core/prisma/prisma.service';
import { AiService } from '../ai/ai.service';
import { JwtAuthGuard } from '../../core/guards/jwt-auth.guard';

const PLAN_UUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890';
const BUSINESS_UUID = 'b2c3d4e5-f6a7-8901-bcde-f12345678901';

const fakePlan = {
  id: PLAN_UUID,
  businessId: BUSINESS_UUID,
  title: 'Test Plan',
  description: 'Test description',
  status: 'Draft' as const,
  mode: 'manual' as const,
  createdAt: new Date(),
};

const fakePosts = [{ day: 1, platform: 'instagram', content: 'Post 1' }];

const fakeBusiness = { id: BUSINESS_UUID, name: 'Test Business' };

// ─────────────────────────────────────────────
// ContentPlanService (unit)
// ─────────────────────────────────────────────
describe('ContentPlanService', () => {
  let module: TestingModule;
  let service: ContentPlanService;
  let mockPrisma: {
    contentPlan: jest.Mocked<{
      findMany: jest.Mock;
      findUnique: jest.Mock;
      create: jest.Mock;
      update: jest.Mock;
      delete: jest.Mock;
    }>;
    business: jest.Mocked<{ findUnique: jest.Mock }>;
    targetAudience: jest.Mocked<{ findMany: jest.Mock }>;
    product: jest.Mocked<{ findMany: jest.Mock }>;
    idea: jest.Mocked<{ findMany: jest.Mock }>;
    ideaAI: jest.Mocked<{ findMany: jest.Mock }>;
  };
  let mockAiService: jest.Mocked<Pick<AiService, 'generateContentPlan'>>;

  const fakeAiResult = {
    title: 'AI Generated Plan',
    description: 'A plan generated by AI',
    posts: [{ day: 1, platform: 'instagram', content: 'Post content' }],
  };

  beforeAll(async () => {
    mockPrisma = {
      contentPlan: {
        findMany: jest.fn(),
        findUnique: jest.fn(),
        create: jest.fn(),
        update: jest.fn(),
        delete: jest.fn(),
      },
      business: { findUnique: jest.fn() },
      targetAudience: { findMany: jest.fn() },
      product: { findMany: jest.fn() },
      idea: { findMany: jest.fn() },
      ideaAI: { findMany: jest.fn() },
    };

    mockAiService = {
      generateContentPlan: jest.fn().mockResolvedValue(fakeAiResult),
    };

    module = await Test.createTestingModule({
      imports: [ConfigModule.forRoot({ isGlobal: true })],
      providers: [
        ContentPlanService,
        { provide: PrismaService, useValue: mockPrisma },
        { provide: AiService, useValue: mockAiService },
      ],
    }).compile();

    service = module.get<ContentPlanService>(ContentPlanService);
  });

  afterAll(async () => {
    await module.close();
  });

  beforeEach(() => {
    jest.clearAllMocks();
    mockAiService.generateContentPlan.mockResolvedValue(fakeAiResult);
  });

  // ─────────────────────────────────────────────
  // getContentPlans
  // ─────────────────────────────────────────────
  describe('getContentPlans', () => {
    it('returns content plans for the given business', async () => {
      mockPrisma.contentPlan.findMany.mockResolvedValue([fakePlan]);

      const result = await service.getContentPlans(BUSINESS_UUID);

      expect(Array.isArray(result)).toBe(true);
      expect(result).toHaveLength(1);
      expect(result[0].businessId).toBe(BUSINESS_UUID);
    });

    it('queries with the correct businessId filter', async () => {
      mockPrisma.contentPlan.findMany.mockResolvedValue([]);

      await service.getContentPlans(BUSINESS_UUID);

      expect(mockPrisma.contentPlan.findMany).toHaveBeenCalledWith(
        expect.objectContaining({
          where: { businessId: BUSINESS_UUID },
        }),
      );
    });

    it('does not select postsJson in the query', async () => {
      mockPrisma.contentPlan.findMany.mockResolvedValue([]);

      await service.getContentPlans(BUSINESS_UUID);

      const callArgs = mockPrisma.contentPlan.findMany.mock.calls[0][0];
      expect(callArgs.select).toBeDefined();
      expect(callArgs.select.postsJson).toBeUndefined();
    });

    it('returns empty array when business has no plans', async () => {
      mockPrisma.contentPlan.findMany.mockResolvedValue([]);

      const result = await service.getContentPlans(BUSINESS_UUID);

      expect(result).toEqual([]);
    });
  });

  // ─────────────────────────────────────────────
  // getContentPlanPosts
  // ─────────────────────────────────────────────
  describe('getContentPlanPosts', () => {
    it('returns postsJson for an existing content plan', async () => {
      mockPrisma.contentPlan.findUnique.mockResolvedValue({
        postsJson: fakePosts,
      });

      const result = await service.getContentPlanPosts(PLAN_UUID);

      expect(result).toEqual(fakePosts);
    });

    it('queries by the correct id', async () => {
      mockPrisma.contentPlan.findUnique.mockResolvedValue({
        postsJson: fakePosts,
      });

      await service.getContentPlanPosts(PLAN_UUID);

      expect(mockPrisma.contentPlan.findUnique).toHaveBeenCalledWith(
        expect.objectContaining({ where: { id: PLAN_UUID } }),
      );
    });

    it('throws NotFoundException when the plan does not exist', async () => {
      mockPrisma.contentPlan.findUnique.mockResolvedValue(null);

      await expect(service.getContentPlanPosts(PLAN_UUID)).rejects.toThrow(
        NotFoundException,
      );
    });
  });

  // ─────────────────────────────────────────────
  // generateContentPlan
  // ─────────────────────────────────────────────
  describe('generateContentPlan', () => {
    beforeEach(() => {
      mockPrisma.business.findUnique.mockResolvedValue(fakeBusiness);
      mockPrisma.targetAudience.findMany.mockResolvedValue([]);
      mockPrisma.product.findMany.mockResolvedValue([]);
      mockPrisma.idea.findMany.mockResolvedValue([]);
      mockPrisma.ideaAI.findMany.mockResolvedValue([]);
      mockPrisma.contentPlan.create.mockResolvedValue({
        ...fakePlan,
        postsJson: fakeAiResult.posts,
      });
    });

    it('throws NotFoundException when business does not exist', async () => {
      mockPrisma.business.findUnique.mockResolvedValue(null);

      await expect(
        service.generateContentPlan(BUSINESS_UUID, { mode: 'manual' }),
      ).rejects.toThrow(NotFoundException);

      expect(mockAiService.generateContentPlan).not.toHaveBeenCalled();
    });

    it('calls AiService.generateContentPlan and creates a ContentPlan record', async () => {
      await service.generateContentPlan(BUSINESS_UUID, { mode: 'manual' });

      expect(mockAiService.generateContentPlan).toHaveBeenCalledTimes(1);
      expect(mockPrisma.contentPlan.create).toHaveBeenCalledTimes(1);
    });

    it('persists the AI result with correct businessId and mode manual', async () => {
      await service.generateContentPlan(BUSINESS_UUID, { mode: 'manual' });

      expect(mockPrisma.contentPlan.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({
            businessId: BUSINESS_UUID,
            title: fakeAiResult.title,
            description: fakeAiResult.description,
            mode: 'manual',
            postsJson: fakeAiResult.posts,
          }),
        }),
      );
    });

    it('saves mode as "profile" when dto.mode is "profile"', async () => {
      await service.generateContentPlan(BUSINESS_UUID, { mode: 'profile' });

      expect(mockPrisma.contentPlan.create).toHaveBeenCalledWith(
        expect.objectContaining({
          data: expect.objectContaining({ mode: 'profile' }),
        }),
      );
    });

    it('passes context to AiService when provided', async () => {
      await service.generateContentPlan(BUSINESS_UUID, {
        mode: 'manual',
        context: 'Focus on summer promotions',
      });

      const callArgs = mockAiService.generateContentPlan.mock.calls[0][0];
      expect(callArgs.context).toBe('Focus on summer promotions');
    });

    it('fetches audiences and products from DB when manual mode with IDs', async () => {
      const fakeAudience = { id: 'aud-1', name: 'Audience 1' };
      const fakeProduct = { id: 'prod-1', name: 'Product 1' };
      mockPrisma.targetAudience.findMany.mockResolvedValue([fakeAudience]);
      mockPrisma.product.findMany.mockResolvedValue([fakeProduct]);

      await service.generateContentPlan(BUSINESS_UUID, {
        mode: 'manual',
        audiencesIds: ['aud-1'],
        productsIds: ['prod-1'],
      });

      const callArgs = mockAiService.generateContentPlan.mock.calls[0][0];
      expect(callArgs.audiences).toContainEqual(fakeAudience);
      expect(callArgs.products).toContainEqual(fakeProduct);
    });

    it('fetches both manual and AI ideas when ideasIds are provided', async () => {
      const manualIdea = { id: 'idea-1', text: 'Manual idea' };
      const aiIdea = { id: 'idea-2', text: 'AI idea' };
      mockPrisma.idea.findMany.mockResolvedValue([manualIdea]);
      mockPrisma.ideaAI.findMany.mockResolvedValue([aiIdea]);

      await service.generateContentPlan(BUSINESS_UUID, {
        mode: 'manual',
        ideasIds: ['idea-1', 'idea-2'],
      });

      const callArgs = mockAiService.generateContentPlan.mock.calls[0][0];
      expect(callArgs.ideas).toContainEqual(manualIdea);
      expect(callArgs.ideas).toContainEqual(aiIdea);
    });

    it('skips audience/product/idea queries when mode is "profile"', async () => {
      await service.generateContentPlan(BUSINESS_UUID, { mode: 'profile' });

      expect(mockPrisma.targetAudience.findMany).not.toHaveBeenCalled();
      expect(mockPrisma.product.findMany).not.toHaveBeenCalled();
      expect(mockPrisma.idea.findMany).not.toHaveBeenCalled();
    });
  });

  // ─────────────────────────────────────────────
  // updateContentPlan
  // ─────────────────────────────────────────────
  describe('updateContentPlan', () => {
    it('throws NotFoundException when the plan does not exist', async () => {
      mockPrisma.contentPlan.findUnique.mockResolvedValue(null);

      await expect(
        service.updateContentPlan(PLAN_UUID, { title: 'New Title' }),
      ).rejects.toThrow(NotFoundException);

      expect(mockPrisma.contentPlan.update).not.toHaveBeenCalled();
    });

    it('updates and returns the plan when it exists', async () => {
      const updatedPlan = { ...fakePlan, title: 'Updated Title' };
      mockPrisma.contentPlan.findUnique.mockResolvedValue(fakePlan);
      mockPrisma.contentPlan.update.mockResolvedValue(updatedPlan);

      const result = await service.updateContentPlan(PLAN_UUID, {
        title: 'Updated Title',
      });

      expect(result.title).toBe('Updated Title');
      expect(mockPrisma.contentPlan.update).toHaveBeenCalledWith(
        expect.objectContaining({ where: { id: PLAN_UUID } }),
      );
    });

    it('passes status field to update', async () => {
      mockPrisma.contentPlan.findUnique.mockResolvedValue(fakePlan);
      mockPrisma.contentPlan.update.mockResolvedValue({
        ...fakePlan,
        status: 'Active' as const,
      });

      const result = await service.updateContentPlan(PLAN_UUID, {
        status: 'Active',
      });

      expect(result.status).toBe('Active');
    });
  });

  // ─────────────────────────────────────────────
  // deleteContentPlan
  // ─────────────────────────────────────────────
  describe('deleteContentPlan', () => {
    it('throws NotFoundException when the plan does not exist', async () => {
      mockPrisma.contentPlan.findUnique.mockResolvedValue(null);

      await expect(service.deleteContentPlan(PLAN_UUID)).rejects.toThrow(
        NotFoundException,
      );

      expect(mockPrisma.contentPlan.delete).not.toHaveBeenCalled();
    });

    it('deletes and returns the plan when it exists', async () => {
      mockPrisma.contentPlan.findUnique.mockResolvedValue(fakePlan);
      mockPrisma.contentPlan.delete.mockResolvedValue(fakePlan);

      const result = await service.deleteContentPlan(PLAN_UUID);

      expect(result.id).toBe(PLAN_UUID);
      expect(mockPrisma.contentPlan.delete).toHaveBeenCalledWith({
        where: { id: PLAN_UUID },
      });
    });
  });
});

// ─────────────────────────────────────────────
// ContentPlanController (integration)
// ─────────────────────────────────────────────
describe('ContentPlanController (integration)', () => {
  let app: INestApplication;
  let mockService: jest.Mocked<
    Pick<
      ContentPlanService,
      | 'getContentPlans'
      | 'getContentPlanPosts'
      | 'generateContentPlan'
      | 'updateContentPlan'
      | 'deleteContentPlan'
    >
  >;

  beforeAll(async () => {
    mockService = {
      getContentPlans: jest.fn().mockResolvedValue([fakePlan]),
      getContentPlanPosts: jest.fn().mockResolvedValue(fakePosts),
      generateContentPlan: jest
        .fn()
        .mockResolvedValue({ ...fakePlan, postsJson: fakePosts }),
      updateContentPlan: jest
        .fn()
        .mockResolvedValue({ ...fakePlan, title: 'Updated' }),
      deleteContentPlan: jest.fn().mockResolvedValue(fakePlan),
    };

    const moduleRef: TestingModule = await Test.createTestingModule({
      imports: [ConfigModule.forRoot({ isGlobal: true })],
      controllers: [ContentPlanController],
      providers: [{ provide: ContentPlanService, useValue: mockService }],
    })
      .overrideGuard(JwtAuthGuard)
      .useValue({ canActivate: () => true })
      .compile();

    app = moduleRef.createNestApplication();
    app.useGlobalPipes(new ValidationPipe({ whitelist: true }));
    await app.init();
  });

  afterAll(async () => {
    await app.close();
  });

  beforeEach(() => {
    jest.clearAllMocks();
    mockService.getContentPlans.mockResolvedValue([fakePlan]);
    mockService.getContentPlanPosts.mockResolvedValue(fakePosts);
    mockService.generateContentPlan.mockResolvedValue({
      ...fakePlan,
      postsJson: fakePosts,
    } as any);
    mockService.updateContentPlan.mockResolvedValue({
      ...fakePlan,
      title: 'Updated',
    } as any);
    mockService.deleteContentPlan.mockResolvedValue(fakePlan as any);
  });

  // ─────────────────────────────────────────────
  // GET /contentPlan/:businessId
  // ─────────────────────────────────────────────
  describe('GET /contentPlan/:businessId', () => {
    it('returns 200 with an array of content plans', async () => {
      const response = await request(app.getHttpServer())
        .get(`/contentPlan/${BUSINESS_UUID}`)
        .expect(200);

      expect(Array.isArray(response.body)).toBe(true);
      expect(mockService.getContentPlans).toHaveBeenCalledWith(BUSINESS_UUID);
    });
  });

  // ─────────────────────────────────────────────
  // GET /contentPlan/posts/:id
  // ─────────────────────────────────────────────
  describe('GET /contentPlan/posts/:id', () => {
    it('returns 200 with posts for a valid plan id', async () => {
      const response = await request(app.getHttpServer())
        .get(`/contentPlan/posts/${PLAN_UUID}`)
        .expect(200);

      expect(response.body).toEqual(fakePosts);
      expect(mockService.getContentPlanPosts).toHaveBeenCalledWith(PLAN_UUID);
    });

    it('returns 404 when plan is not found', async () => {
      mockService.getContentPlanPosts.mockRejectedValue(
        new NotFoundException('Content plan not found'),
      );

      await request(app.getHttpServer())
        .get(`/contentPlan/posts/${PLAN_UUID}`)
        .expect(404);
    });
  });

  // ─────────────────────────────────────────────
  // POST /contentPlan/:businessId
  // ─────────────────────────────────────────────
  describe('POST /contentPlan/:businessId', () => {
    it('returns 201 with the generated plan for valid body', async () => {
      const response = await request(app.getHttpServer())
        .post(`/contentPlan/${BUSINESS_UUID}`)
        .send({ mode: 'manual' })
        .expect(201);

      expect(response.body).toHaveProperty('id');
      expect(mockService.generateContentPlan).toHaveBeenCalledWith(
        BUSINESS_UUID,
        { mode: 'manual' },
      );
    });

    it('returns 201 for profile mode with optional fields omitted', async () => {
      await request(app.getHttpServer())
        .post(`/contentPlan/${BUSINESS_UUID}`)
        .send({ mode: 'profile' })
        .expect(201);

      expect(mockService.generateContentPlan).toHaveBeenCalledWith(
        BUSINESS_UUID,
        { mode: 'profile' },
      );
    });

    it('returns 400 when mode field is missing', async () => {
      await request(app.getHttpServer())
        .post(`/contentPlan/${BUSINESS_UUID}`)
        .send({})
        .expect(400);

      expect(mockService.generateContentPlan).not.toHaveBeenCalled();
    });

    it('returns 400 when productsIds contains non-string values', async () => {
      await request(app.getHttpServer())
        .post(`/contentPlan/${BUSINESS_UUID}`)
        .send({ mode: 'manual', productsIds: [123, 456] })
        .expect(400);

      expect(mockService.generateContentPlan).not.toHaveBeenCalled();
    });

    it('passes optional arrays and context when provided', async () => {
      await request(app.getHttpServer())
        .post(`/contentPlan/${BUSINESS_UUID}`)
        .send({
          mode: 'manual',
          productsIds: ['prod-1'],
          audiencesIds: ['aud-1'],
          ideasIds: ['idea-1'],
          context: 'Summer campaign',
        })
        .expect(201);

      expect(mockService.generateContentPlan).toHaveBeenCalledWith(
        BUSINESS_UUID,
        {
          mode: 'manual',
          productsIds: ['prod-1'],
          audiencesIds: ['aud-1'],
          ideasIds: ['idea-1'],
          context: 'Summer campaign',
        },
      );
    });
  });

  // ─────────────────────────────────────────────
  // PATCH /contentPlan/:id
  // ─────────────────────────────────────────────
  describe('PATCH /contentPlan/:id', () => {
    it('returns 200 with the updated plan', async () => {
      const response = await request(app.getHttpServer())
        .patch(`/contentPlan/${PLAN_UUID}`)
        .send({ title: 'New Title' })
        .expect(200);

      expect(response.body).toHaveProperty('title');
      expect(mockService.updateContentPlan).toHaveBeenCalledWith(PLAN_UUID, {
        title: 'New Title',
      });
    });

    it('returns 200 when updating status', async () => {
      await request(app.getHttpServer())
        .patch(`/contentPlan/${PLAN_UUID}`)
        .send({ status: 'Active' })
        .expect(200);

      expect(mockService.updateContentPlan).toHaveBeenCalledWith(PLAN_UUID, {
        status: 'Active',
      });
    });

    it('returns 404 when plan does not exist', async () => {
      mockService.updateContentPlan.mockRejectedValue(
        new NotFoundException('Content plan not found'),
      );

      await request(app.getHttpServer())
        .patch(`/contentPlan/${PLAN_UUID}`)
        .send({ title: 'Ghost Update' })
        .expect(404);
    });

    it('strips unknown fields from the body (whitelist)', async () => {
      await request(app.getHttpServer())
        .patch(`/contentPlan/${PLAN_UUID}`)
        .send({ title: 'Clean', unknownField: 'should be stripped' })
        .expect(200);

      expect(mockService.updateContentPlan).toHaveBeenCalledWith(PLAN_UUID, {
        title: 'Clean',
      });
    });
  });

  // ─────────────────────────────────────────────
  // DELETE /contentPlan/:id
  // ─────────────────────────────────────────────
  describe('DELETE /contentPlan/:id', () => {
    it('returns 200 when content plan is deleted', async () => {
      await request(app.getHttpServer())
        .delete(`/contentPlan/${PLAN_UUID}`)
        .expect(200);

      expect(mockService.deleteContentPlan).toHaveBeenCalledWith(PLAN_UUID);
    });

    it('returns 404 when plan does not exist', async () => {
      mockService.deleteContentPlan.mockRejectedValue(
        new NotFoundException('Content plan not found'),
      );

      await request(app.getHttpServer())
        .delete(`/contentPlan/${PLAN_UUID}`)
        .expect(404);
    });
  });
});
