import { Injectable } from '@nestjs/common';
import { GoogleAuth } from 'google-auth-library';
import { randomUUID } from "crypto";
import { S3Service } from "../../core/s3/s3.service";

@Injectable()
export class AiVertexImage {
  private readonly project = process.env.GOOGLE_PROJECT_ID!;
  private readonly location = process.env.GOOGLE_PROJECT_LOCATION || 'europe-central2';
  private readonly model = 'imagen-3.0-generate-001';

  constructor(
    private readonly s3Service: S3Service,
  ) {}

  async generateImage(prompt: string, businessId: string): Promise<string> {
    console.log("GENERATE IMAGE...")
    const auth = new GoogleAuth({
      scopes: ['https://www.googleapis.com/auth/cloud-platform'],
    });

    console.log("111")

    const client = await auth.getClient();

    console.log("222")

    const accessToken = await client.getAccessToken();

    console.log("333")

    console.log("Prompt ", prompt)

    const response = await fetch(
      `https://${this.location}-aiplatform.googleapis.com/v1/projects/${this.project}/locations/${this.location}/publishers/google/models/${this.model}:predict`,
      {
        method: 'POST',
        headers: {
          Authorization: `Bearer ${accessToken.token}`,
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          instances: [
            {
              prompt: "Photorealistic action shot of professional adult football players\n" +
                "playing a competitive match on a modern football stadium.\n" +
                "Natural daylight, clear sky.\n" +
                "Dynamic movement, realistic body proportions, detailed sports uniforms.\n" +
                "Shot on a professional DSLR camera, telephoto lens,\n" +
                "shallow depth of field, cinematic sports photography.\n" +
                "Ultra high resolution, realistic lighting, no illustration, no cartoon.",
            },
          ],
          parameters: {
            sampleCount: 1,
            aspectRatio: '1:1',
          },
        }),
      },
    );

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`Imagen HTTP error: ${response.status} ${errText}`);
    }

    const raw = await response.text();
    console.log('IMAGEN RAW RESPONSE:', raw);

    const data = JSON.parse(raw);

    console.log("DATA ", data)

    if (!data.predictions || data.predictions.length === 0) {
      console.error('Imagen returned no predictions', data);
      throw new Error('No image generated by Imagen');
    }

    const prediction = data.predictions[0];

    console.log("PREDICTION ", prediction)

    const imageBase64 =
      prediction.bytesBase64Encoded ||
      prediction.image?.bytesBase64Encoded;


    if (!imageBase64) {
      console.error('Unexpected Imagen response format', prediction);
      throw new Error('Invalid image response format from Imagen');
    }

    console.log(imageBase64)
    console.log("666")

    const buffer = Buffer.from(imageBase64, 'base64');
    const fileName = `${randomUUID()}.png`;
    const key = `ai-images/${businessId}/${fileName}`;

    await this.s3Service.upload(
      key,
      buffer,
      "image/png"
    );

    console.log("----------")
    console.log("KEY ", `https://crm-marketing-ai-bucket.s3.eu-north-1.amazonaws.com/${key}`);
    console.log("----------")

    return key;
  }
}