-- AlterTable
ALTER TABLE "FacebookReport"
DROP COLUMN "adsCtaMessages",
DROP COLUMN "adsCtaLinks",
DROP COLUMN "adsCtaOther",
ADD COLUMN "adsCtaWebsite" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "adsCtaDirectMessage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "adsCtaInstagramPage" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "adsCtaProduct" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "adsCtaMetaPage" INTEGER NOT NULL DEFAULT 0;
